<a href="https://colab.research.google.com/github/MaxCojocari/ML_Express_Tekwill/blob/main/ML_Express_HW3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

In [30]:
models = [
    KNeighborsClassifier(),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    LogisticRegression(),
    GaussianNB()
]

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler

In [32]:
str_col = ['Sex','ChestPainType','RestingECG','ExerciseAngina','ST_Slope']

In [33]:
df = pd.read_csv('/content/drive/MyDrive/ML_Express/heart.csv')
df

     Age Sex ChestPainType  ...  Oldpeak  ST_Slope  HeartDisease
0     40   M           ATA  ...      0.0        Up             0
1     49   F           NAP  ...      1.0      Flat             1
2     37   M           ATA  ...      0.0        Up             0
3     48   F           ASY  ...      1.5      Flat             1
4     54   M           NAP  ...      0.0        Up             0
..   ...  ..           ...  ...      ...       ...           ...
913   45   M            TA  ...      1.2      Flat             1
914   68   M           ASY  ...      3.4      Flat             1
915   57   M           ASY  ...      1.2      Flat             1
916   57   F           ATA  ...      0.0      Flat             1
917   38   M           NAP  ...      0.0        Up             0

[918 rows x 12 columns]

In [34]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
df[str_col] = df[str_col].apply(lb.fit_transform)

In [35]:
df

     Age  Sex  ChestPainType  ...  Oldpeak  ST_Slope  HeartDisease
0     40    1              1  ...      0.0         2             0
1     49    0              2  ...      1.0         1             1
2     37    1              1  ...      0.0         2             0
3     48    0              0  ...      1.5         1             1
4     54    1              2  ...      0.0         2             0
..   ...  ...            ...  ...      ...       ...           ...
913   45    1              3  ...      1.2         1             1
914   68    1              0  ...      3.4         1             1
915   57    1              0  ...      1.2         1             1
916   57    0              1  ...      0.0         1             1
917   38    1              2  ...      0.0         2             0

[918 rows x 12 columns]

In [40]:
def test_model(df, models, target):
    X = df.drop([target], axis=1).values
    y = df[target].values
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
    
    mse, mae, mse_normalized, mae_normalized = {}, {}, {}, {}
    scaler = StandardScaler()
    
    for i in range(len(models)):
        models[i].fit(X_train, y_train)
        y_pred = models[i].predict(X_test)
        
        mae[str(models[i].__class__())] = mean_absolute_error(y_pred, y_test)
        mse[str(models[i].__class__())] = mean_squared_error(y_pred, y_test)
        
        X_train_norm = scaler.fit_transform(X_train)
        X_test_norm = scaler.transform(X_test)
        
        models[i].fit(X_train_norm, y_train)
        y_pred = models[i].predict(X_test_norm)
        
        mse_normalized[str(models[i].__class__())] = mean_squared_error(y_pred, y_test)
        mae_normalized[str(models[i].__class__())] = mean_absolute_error(y_pred, y_test)
    
    return mae, mse, mae_normalized, mse_normalized

In [41]:
mae, mse, mae_normalized, mse_normalized = test_model(df, models, 'HeartDisease')

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,